### ISSUE TITLE
issues with experimentation (CHECKLIST)

### ISSUE THREAD

**Issue by BenedictWilkins** [dicelab-rhul/ICU#36]
Various things need updating to make experiments easier to analysis later.
- [ ] give an option to place eye tracking events in a different file (they flood the log file)
- [ ] standardize the input event format
- [ ] when logging changes, also log the current value (e.g. fuel change -1, **value 100**) this makes it easier to process the file and is less error prone.
- [ ] have a mode where agents give "fake" feedback (not shown on the interface, but logged) so that we can do counter factual analysis more easily.
- [ ] show more obvious warning if the eye tracking system crashes so that the experimenter can be aware!
- [ ] position of the target in the tracking task is not in window coordinates. The position of the tracking task should be given in a log file. Complete window information (can use window_properties in __init__.py) should be logged.
- [ ] when eyes move out of the ICU interface window this should be known, add a new label "outofbounds"
- [ ] eye tracking timestamp is wrong, it is current "time since eye-tracker has been on"
- [ ] it would be good to include a start up or "ready" event with a timestamp 
- [ ]  record all mouse and keyboard input regardless of whether it is a "valid" interaction.
- [ ] there should be an event triggered when a task is "in failure", this is only true for the fuel task, make it so for the others.
- [ ] the "cause" property of an event is difficult to parse, it should just be the ID of the causing event.
